version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5002:5002"
    # volumes:
    #   - ./backend:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: npx nodemon index.js

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: npm start
    depends_on:
      - backend
